title: Now
description: What I'm doing now
url: ""
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  sections:
    output: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
